// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Torchbearer.Infrastructure.Persistence;

#nullable disable

namespace Torchbearer.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TorchbearerDbContext))]
    [Migration("20260111121717_AddCharacterManagement")]
    partial class AddCharacterManagement
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Torchbearer.Domain.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Gold")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ImageFileName")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Hex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HexMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Q")
                        .HasColumnType("INTEGER");

                    b.Property<int>("R")
                        .HasColumnType("INTEGER");

                    b.Property<int>("S")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TQ")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TR")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TS")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TerrainTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TerrainTypeId");

                    b.HasIndex("HexMapId", "Q", "R", "S")
                        .IsUnique();

                    b.ToTable("Hexes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.HexMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CharacterId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CharacterId")
                        .IsUnique();

                    b.ToTable("HexMaps");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxCharacterSlots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PlayerRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PlayerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("PlayerId", "RoleId")
                        .IsUnique();

                    b.ToTable("PlayerRoles");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PointOfInterestHex", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HexId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HexMapId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PointOfInterestId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("HexId");

                    b.HasIndex("PointOfInterestId");

                    b.HasIndex("HexMapId", "HexId", "PointOfInterestId")
                        .IsUnique();

                    b.ToTable("PointOfInterestHexes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 2,
                            Name = "DM"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.TerrainType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TerrainTypes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Character", b =>
                {
                    b.HasOne("Torchbearer.Domain.Entities.Player", "Player")
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Hex", b =>
                {
                    b.HasOne("Torchbearer.Domain.Entities.HexMap", "HexMap")
                        .WithMany("Hexes")
                        .HasForeignKey("HexMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torchbearer.Domain.Entities.TerrainType", "TerrainType")
                        .WithMany("Hexes")
                        .HasForeignKey("TerrainTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HexMap");

                    b.Navigation("TerrainType");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.HexMap", b =>
                {
                    b.HasOne("Torchbearer.Domain.Entities.Character", "Character")
                        .WithOne("HexMap")
                        .HasForeignKey("Torchbearer.Domain.Entities.HexMap", "CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PlayerRole", b =>
                {
                    b.HasOne("Torchbearer.Domain.Entities.Player", "Player")
                        .WithMany("PlayerRoles")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torchbearer.Domain.Entities.Role", "Role")
                        .WithMany("PlayerRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PointOfInterestHex", b =>
                {
                    b.HasOne("Torchbearer.Domain.Entities.Hex", "Hex")
                        .WithMany("PointOfInterestHexes")
                        .HasForeignKey("HexId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Torchbearer.Domain.Entities.HexMap", "HexMap")
                        .WithMany()
                        .HasForeignKey("HexMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Torchbearer.Domain.Entities.PointOfInterest", "PointOfInterest")
                        .WithMany("PointOfInterestHexes")
                        .HasForeignKey("PointOfInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hex");

                    b.Navigation("HexMap");

                    b.Navigation("PointOfInterest");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Character", b =>
                {
                    b.Navigation("HexMap");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Hex", b =>
                {
                    b.Navigation("PointOfInterestHexes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.HexMap", b =>
                {
                    b.Navigation("Hexes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Player", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("PlayerRoles");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.PointOfInterest", b =>
                {
                    b.Navigation("PointOfInterestHexes");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.Role", b =>
                {
                    b.Navigation("PlayerRoles");
                });

            modelBuilder.Entity("Torchbearer.Domain.Entities.TerrainType", b =>
                {
                    b.Navigation("Hexes");
                });
#pragma warning restore 612, 618
        }
    }
}
